[[protocols]]
name = "astrometa_t2hybrid"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x4d = "KEY_POWER2"
0x54 = "KEY_VIDEO"
0x16 = "KEY_MUTE"
0x4c = "KEY_RECORD"
0x05 = "KEY_CHANNELUP"
0x0c = "KEY_TIME"
0x0a = "KEY_VOLUMEDOWN"
0x40 = "KEY_ZOOM"
0x1e = "KEY_VOLUMEUP"
0x12 = "KEY_0"
0x02 = "KEY_CHANNELDOWN"
0x1c = "KEY_AGAIN"
0x09 = "KEY_1"
0x1d = "KEY_2"
0x1f = "KEY_3"
0x0d = "KEY_4"
0x19 = "KEY_5"
0x1b = "KEY_6"
0x11 = "KEY_7"
0x15 = "KEY_8"
0x17 = "KEY_9"
