[[protocols]]
name = "behold"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x866b1c = "KEY_TUNER"
0x866b12 = "KEY_POWER"
0x866b01 = "KEY_1"
0x866b02 = "KEY_2"
0x866b03 = "KEY_3"
0x866b04 = "KEY_4"
0x866b05 = "KEY_5"
0x866b06 = "KEY_6"
0x866b07 = "KEY_7"
0x866b08 = "KEY_8"
0x866b09 = "KEY_9"
0x866b0a = "KEY_AGAIN"
0x866b00 = "KEY_0"
0x866b17 = "KEY_MODE"
0x866b14 = "KEY_SCREEN"
0x866b10 = "KEY_ZOOM"
0x866b0b = "KEY_CHANNELUP"
0x866b18 = "KEY_VOLUMEDOWN"
0x866b16 = "KEY_OK"
0x866b0c = "KEY_VOLUMEUP"
0x866b15 = "KEY_CHANNELDOWN"
0x866b11 = "KEY_MUTE"
0x866b0d = "KEY_INFO"
0x866b0f = "KEY_RECORD"
0x866b1b = "KEY_PLAYPAUSE"
0x866b1a = "KEY_STOP"
0x866b0e = "KEY_TEXT"
0x866b1f = "KEY_RED"
0x866b1e = "KEY_VIDEO"
0x866b1d = "KEY_SLEEP"
0x866b13 = "KEY_GREEN"
0x866b19 = "KEY_BLUE"
0x866b58 = "KEY_SLOW"
0x866b5c = "KEY_CAMERA"
