[[protocols]]
name = "dvico_portable"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x0302 = "KEY_SETUP"
0x0343 = "KEY_POWER2"
0x0306 = "KEY_EPG"
0x035a = "KEY_BACK"
0x0305 = "KEY_MENU"
0x0347 = "KEY_INFO"
0x0301 = "KEY_TAB"
0x0342 = "KEY_PREVIOUSSONG"
0x0349 = "KEY_VOLUMEUP"
0x0309 = "KEY_VOLUMEDOWN"
0x0354 = "KEY_CHANNELUP"
0x030b = "KEY_CHANNELDOWN"
0x0316 = "KEY_CAMERA"
0x0340 = "KEY_TUNER"
0x0345 = "KEY_OPEN"
0x0319 = "KEY_1"
0x0318 = "KEY_2"
0x031b = "KEY_3"
0x031a = "KEY_4"
0x0358 = "KEY_5"
0x0359 = "KEY_6"
0x0315 = "KEY_7"
0x0314 = "KEY_8"
0x0317 = "KEY_9"
0x0344 = "KEY_ANGLE"
0x0355 = "KEY_0"
0x0307 = "KEY_ZOOM"
0x030a = "KEY_REWIND"
0x0308 = "KEY_PLAYPAUSE"
0x034b = "KEY_FASTFORWARD"
0x035b = "KEY_MUTE"
0x0304 = "KEY_STOP"
0x0356 = "KEY_RECORD"
0x0357 = "KEY_POWER"
0x0341 = "KEY_UNKNOWN"
0x0300 = "KEY_UNKNOWN"
