[[protocols]]
name = "hisi_poplar"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x0000b292 = "KEY_1"
0x0000b293 = "KEY_2"
0x0000b2cc = "KEY_3"
0x0000b28e = "KEY_4"
0x0000b28f = "KEY_5"
0x0000b2c8 = "KEY_6"
0x0000b28a = "KEY_7"
0x0000b28b = "KEY_8"
0x0000b2c4 = "KEY_9"
0x0000b287 = "KEY_0"
0x0000b282 = "KEY_HOMEPAGE"
0x0000b2ca = "KEY_UP"
0x0000b299 = "KEY_LEFT"
0x0000b2c1 = "KEY_RIGHT"
0x0000b2d2 = "KEY_DOWN"
0x0000b2c5 = "KEY_DELETE"
0x0000b29c = "KEY_MUTE"
0x0000b281 = "KEY_VOLUMEDOWN"
0x0000b280 = "KEY_VOLUMEUP"
0x0000b2dc = "KEY_POWER"
0x0000b29a = "KEY_MENU"
0x0000b28d = "KEY_SETUP"
0x0000b2c5 = "KEY_BACK"
0x0000b295 = "KEY_PLAYPAUSE"
0x0000b2ce = "KEY_ENTER"
0x0000b285 = "KEY_CHANNELUP"
0x0000b286 = "KEY_CHANNELDOWN"
0x0000b2da = "KEY_NUMERIC_STAR"
0x0000b2d0 = "KEY_NUMERIC_POUND"
